server:
  port: 8080
  #ssl:
    #key-store: classpath:server/soapservice_keystore.jks
    #key-store-password: s3cr3t
    #key-alias: service
    #key-password: s3cr3t
    #trust-store: classpath:server/soapservice_truststore.jks
    #trust-store-password: s3cr3t
    #client-auth: want
    #protocol: TLSv1.2